### ISSUE TITLE
Support multipart/form-data

### ISSUE THREAD

**Issue by jeremy-carbonne** [Place1/swagger-codegen-typescript-browser#1]
Hi,

The generated `uploadFile` function define a content type x-www-form-urlencoded:
```headerParameters['Content-Type'] = 'application/x-www-form-urlencoded';```

But in the `swagger.json` has:
```
"consumes": [
    "multipart/form-data"
],
```

(The request POST a correct formData)

**Comment by Place1** [comment]
@jeremy-carbonne i've fixed this in #4

**Comment by jeremy-carbonne** [comment]
Fixed #5
